<?php

/**
 * This is the model base class for the table "blocks".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Blocks".
 *
 * Columns in table "blocks" available as properties of the model,
 * followed by relations of table "blocks" available as properties of the model.
 *
 * @property string $id
 * @property string $user_id
 * @property string $blocked_user_id
 * @property integer $blocked
 *
 * @property Users $blockedUser
 * @property Users $user
 */
abstract class BaseBlocks extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'blocks';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Blocks|Blocks', $n);
	}

	public static function representingColumn() {
		return 'create_date';
	}

	public function rules() {
		return array(
			array('user_id, blocked_user_id, create_date', 'required'),
			array('update_date', 'required', 'on' => 'update'),
			array('blocked', 'numerical', 'integerOnly'=>true),
			array('user_id, blocked_user_id', 'length', 'max'=>10),
			array('delete_date', 'safe'),
			array('blocked, delete_date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, blocked_user_id, blocked, create_date, update_date, delete_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'contactUser' => array(self::BELONGS_TO, 'Users', 'blocked_user_id'),
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'blocked_user_id' => null,
			'blocked' => Yii::t('app', 'Blocked'),
			'create_date' => Yii::t('app', 'Create Date'),
			'update_date' => Yii::t('app', 'Update Date'),
			'delete_date' => Yii::t('app', 'Delete Date'),
			'blockedUser' => null,
			'user' => null,
		);
	}

	public function beforeValidate() {
		if($this->isNewRecord) { $this->create_date = date('Y-m-d H:i:s'); }
		else { $this->update_date = date('Y-m-d H:i:s'); }

		return true;
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('bloced_user_id', $this->blocked_user_id);
		$criteria->compare('blocked', $this->blocked);
		$criteria->compare('create_date', $this->create_date, true);
		$criteria->compare('update_date', $this->update_date, true);
		$criteria->compare('delete_date', $this->delete_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}