<?php

/**
 * This is the model base class for the table "content_types".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ContentTypes".
 *
 * Columns in table "content_types" available as properties of the model,
 * followed by relations of table "content_types" available as properties of the model.
 *
 * @property string $id
 * @property string $type
 *
 * @property Contents[] $contents
 */
abstract class BaseContentTypes extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'content_types';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ContentTypes|ContentTypes', $n);
	}

	public static function representingColumn() {
		return 'type';
	}

	public function rules() {
		return array(
			array('type', 'required'),
			array('type', 'length', 'max'=>255),
			array('id, type', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'contents' => array(self::HAS_MANY, 'Contents', 'content_type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'type' => Yii::t('app', 'Type'),
			'contents' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('type', $this->type, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}