<?php

/**
 * This is the model base class for the table "preferences".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Preferences".
 *
 * Columns in table "preferences" available as properties of the model,
 * followed by relations of table "preferences" available as properties of the model.
 *
 * @property string $id
 * @property string $user_id
 * @property string $name
 * @property string $value
 * @property string $create_date
 * @property string $update_date
 *
 * @property Users $user
 */
abstract class BasePreferences extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'preferences';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Preferences|Preferences', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('user_id, name, value, create_date, update_date', 'required'),
			array('user_id', 'length', 'max'=>10),
			array('name', 'length', 'max'=>255),
			array('id, user_id, name, value, create_date, update_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'name' => Yii::t('app', 'Name'),
			'value' => Yii::t('app', 'Value'),
			'create_date' => Yii::t('app', 'Create Date'),
			'update_date' => Yii::t('app', 'Update Date'),
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('value', $this->value, true);
		$criteria->compare('create_date', $this->create_date, true);
		$criteria->compare('update_date', $this->update_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}