<?php

/**
 * This is the model base class for the table "products".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Products".
 *
 * Columns in table "products" available as properties of the model,
 * followed by relations of table "products" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $description
 * @property string $ios_product_id
 * @property string $android_product_id
 * @property string $create_date
 * @property string $update_date
 * @property string $delete_date
 *
 * @property Contents[] $contents
 * @property Users[] $users
 */
abstract class BaseProducts extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'products';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Products|Products', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, description, ios_product_id, android_product_id, create_date, update_date', 'required'),
			array('name', 'length', 'max'=>255),
			array('ios_product_id, android_product_id', 'length', 'max'=>1024),
			array('delete_date', 'safe'),
			array('delete_date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, description, ios_product_id, android_product_id, create_date, update_date, delete_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'contents' => array(self::HAS_MANY, 'Contents', 'product_id'),
			'users' => array(self::MANY_MANY, 'Users', 'products_users(product_id, user_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'users' => 'ProductsUsers',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'ios_product_id' => Yii::t('app', 'Ios Product'),
			'android_product_id' => Yii::t('app', 'Android Product'),
			'create_date' => Yii::t('app', 'Create Date'),
			'update_date' => Yii::t('app', 'Update Date'),
			'delete_date' => Yii::t('app', 'Delete Date'),
			'contents' => null,
			'users' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('ios_product_id', $this->ios_product_id, true);
		$criteria->compare('android_product_id', $this->android_product_id, true);
		$criteria->compare('create_date', $this->create_date, true);
		$criteria->compare('update_date', $this->update_date, true);
		$criteria->compare('delete_date', $this->delete_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}