<?php

/**
 * This is the model base class for the table "facebook_friends".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FacebookFriends".
 *
 * Columns in table "facebook_friends" available as properties of the model,
 * followed by relations of table "facebook_friends" available as properties of the model.
 *
 * @property integer $id
 * @property string $user_id
 * @property string $facebook_id
 * @property string $email
 * @property string $create_date
 * @property string $update_date
 * @property string $delete_date
 *
 * @property Users $user
 */
abstract class BaseFacebookFriends extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'facebook_friends';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FacebookFriends|FacebookFriends', $n);
	}

	public static function representingColumn() {
		return 'facebook_id';
	}

	public function rules() {
		return array(
			array('user_id, facebook_id', 'required'),
			array('user_id', 'length', 'max'=>10),
			array('facebook_id', 'length', 'max'=>50),
			array('email', 'length', 'max'=>128),
			array('email', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, facebook_id, email, create_date, update_date, delete_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
			'devices' => array(self::HAS_MANY, 'Devices', array('id'=>'user_id') ,'through'=>  'user'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'facebook_id' => Yii::t('app', 'Facebook'),
			'email' => Yii::t('app', 'Email'),
			'create_date' => Yii::t('app', 'Create Date'),
			'update_date' => Yii::t('app', 'Update Date'),
			'delete_date' => Yii::t('app', 'Delete Date'),
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('facebook_id', $this->facebook_id, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('create_date', $this->create_date, true);
		$criteria->compare('update_date', $this->update_date, true);
		$criteria->compare('delete_date', $this->delete_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}