<?php

/**
 * This is the model base class for the table "group_members".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GroupMembers".
 *
 * Columns in table "group_members" available as properties of the model,
 * followed by relations of table "group_members" available as properties of the model.
 *
 * @property string $id
 * @property string $group_id
 * @property string $user_id
 * @property integer $accepted
 * @property integer $removed
 * @property string $create_date
 * @property string $update_date
 * @property string $delete_date
 *
 * @property Groups $group
 * @property Users $user
 */
abstract class BaseGroupMembers extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'group_members';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GroupMembers|GroupMembers', $n);
	}

	public static function representingColumn() {
		return 'create_date';
	}

	public function rules() {
		return array(
			array('group_id, user_id', 'required'),
			array('accepted, removed', 'numerical', 'integerOnly'=>true),
			array('group_id, user_id', 'length', 'max'=>10),
			array('delete_date', 'safe'),
			array('accepted, removed, delete_date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, group_id, user_id, accepted, removed, create_date, update_date, delete_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'group' => array(self::BELONGS_TO, 'Groups', 'group_id'),
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'group_id' => null,
			'user_id' => null,
			'accepted' => Yii::t('app', 'Accepted'),
			'removed' => Yii::t('app', 'Removed'),
			'create_date' => Yii::t('app', 'Create Date'),
			'update_date' => Yii::t('app', 'Update Date'),
			'delete_date' => Yii::t('app', 'Delete Date'),
			'group' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('group_id', $this->group_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('accepted', $this->accepted);
		$criteria->compare('removed', $this->removed);
		$criteria->compare('create_date', $this->create_date, true);
		$criteria->compare('update_date', $this->update_date, true);
		$criteria->compare('delete_date', $this->delete_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}