<?php

/**
 * This is the model base class for the table "address_book".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AddressBook".
 *
 * Columns in table "address_book" available as properties of the model,
 * followed by relations of table "address_book" available as properties of the model.
 *
 * @property integer $id
 * @property string $user_id
 * @property string $contact_email
 * @property string $contact_phone
 * @property string $create_date
 * @property string $update_date
 * @property string $delete_date
 *
 * @property Users $user
 */
abstract class BaseAddressBook extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'address_book';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AddressBook|AddressBooks', $n);
	}

	public static function representingColumn() {
		return 'contact_email';
	}

	public function rules() {
		return array(
			array('user_id, contact_email, contact_phone, create_date, update_date', 'required'),
			array('user_id', 'length', 'max'=>10),
			array('contact_email', 'length', 'max'=>50),
			array('contact_phone', 'length', 'max'=>200),
			array('delete_date', 'safe'),
			array('delete_date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, contact_email, contact_phone, create_date, update_date, delete_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
            'devices' => array(self::HAS_MANY, 'Devices', array('id'=>'user_id') ,'through'=>  'user'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'contact_email' => Yii::t('app', 'Contact Email'),
			'contact_phone' => Yii::t('app', 'Contact Phone'),
			'create_date' => Yii::t('app', 'Create Date'),
			'update_date' => Yii::t('app', 'Update Date'),
			'delete_date' => Yii::t('app', 'Delete Date'),
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('contact_email', $this->contact_email, true);
		$criteria->compare('contact_phone', $this->contact_phone, true);
		$criteria->compare('create_date', $this->create_date, true);
		$criteria->compare('update_date', $this->update_date, true);
		$criteria->compare('delete_date', $this->delete_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}