<?php

/**
 * This is the model base class for the table "contents".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Contents".
 *
 * Columns in table "contents" available as properties of the model,
 * followed by relations of table "contents" available as properties of the model.
 *
 * @property string $id
 * @property string $content_type_id
 * @property string $product_id
 * @property string $name
 * @property string $data
 * @property string $create_date
 * @property string $update_date
 * @property string $delete_date
 *
 * @property ContentTypes $contentType
 * @property Products $product
 */
abstract class BaseContents extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'contents';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Contents|Contents', $n);
	}

	public static function representingColumn() {
		return 'create_date';
	}

	public function rules() {
		return array(
			array('content_type_id, create_date, update_date', 'required'),
			array('content_type_id, product_id', 'length', 'max'=>10),
			array('name', 'length', 'max'=>255),
			array('data, delete_date', 'safe'),
			array('product_id, name, data, delete_date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, content_type_id, product_id, name, data, create_date, update_date, delete_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'contentType' => array(self::BELONGS_TO, 'ContentTypes', 'content_type_id'),
			'product' => array(self::BELONGS_TO, 'Products', 'product_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'content_type_id' => null,
			'product_id' => null,
			'name' => Yii::t('app', 'Name'),
			'data' => Yii::t('app', 'Data'),
			'create_date' => Yii::t('app', 'Create Date'),
			'update_date' => Yii::t('app', 'Update Date'),
			'delete_date' => Yii::t('app', 'Delete Date'),
			'contentType' => null,
			'product' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('content_type_id', $this->content_type_id);
		$criteria->compare('product_id', $this->product_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('data', $this->data, true);
		$criteria->compare('create_date', $this->create_date, true);
		$criteria->compare('update_date', $this->update_date, true);
		$criteria->compare('delete_date', $this->delete_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}